sudo: required
dist: trusty
language: node_js
node_js: '11.6'
branches:
  only:
  - master
before_install:
  - git submodule init
  - git submodule update --remote
  - npm install -g yarn --cache-min 999999999
install: 
  - yarn install
script:
  - yarn test
  - yarn build && yarn link.lib
  - sh ./tools/post-build.sh
after_success:
  - yarn coveralls